// <auto-generated />
using System;
using DataAccess;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DataAccess.Migrations
{
    [DbContext(typeof(CaseContext))]
    [Migration("20240429102256_addtoTblDataYedek")]
    partial class addtoTblDataYedek
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Entitities.TblData", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<short>("BirthYear")
                        .HasColumnType("smallint");

                    b.Property<string>("City")
                        .HasMaxLength(50)
                        .HasColumnType("NVarchar(50)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .HasMaxLength(50)
                        .HasColumnType("NVarchar(50)");

                    b.Property<string>("Surname")
                        .HasMaxLength(60)
                        .HasColumnType("NVarchar(60)");

                    b.HasKey("Id");

                    b.ToTable("TblData");
                });

            modelBuilder.Entity("Entitities.TblDataYedek", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<short>("BirthYear")
                        .HasColumnType("smallint");

                    b.Property<string>("City")
                        .HasMaxLength(50)
                        .HasColumnType("NVarchar(50)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .HasMaxLength(50)
                        .HasColumnType("NVarchar(50)");

                    b.Property<string>("Surname")
                        .HasMaxLength(60)
                        .HasColumnType("NVarchar(60)");

                    b.HasKey("Id");

                    b.ToTable("TblDataYedek");
                });
#pragma warning restore 612, 618
        }
    }
}
